import type {
  Event,
  Participant,
  Schedule,
  Group,
  GroupMember,
  AttendanceRecord,
  Announcement,
  Material,
  Quiz,
  QuizQuestion,
  QuizResponse,
  PointRecord,
  GalleryAlbum,
  GalleryPhoto,
} from '@/types'

// ============================================
// Demo Event
// ============================================

export const DEMO_EVENT: Event = {
  id: 'demo-event-1',
  name: '2026 여름수련회',
  type: 'retreat',
  start_date: '2026-07-20',
  end_date: '2026-07-23',
  location: '속초 은혜수련원',
  description: '사랑의교회 중고등부 여름 수련회',
  invite_code: 'FLOW26',
  settings: {},
  created_at: '2026-06-01T00:00:00.000Z',
  updated_at: '2026-07-15T00:00:00.000Z',
}

// ============================================
// Demo Participants (15 people)
// ============================================

export const DEMO_PARTICIPANTS: Participant[] = [
  {
    id: 'p1',
    event_id: 'demo-event-1',
    user_id: null,
    name: '김은혜',
    birth_date: '2012-03-15',
    gender: 'female',
    grade: '중1',
    phone: '010-1234-5678',
    parent_phone: '010-1111-2222',
    emergency_contact: '010-1111-2222',
    health_info: {},
    dietary_restrictions: null,
    transportation: 'bus',
    fee_paid: true,
    consent_personal_info: true,
    consent_sensitive_info: true,
    consent_photo_video: true,
    consent_overseas_transfer: false,
    consent_ip: null,
    created_at: '2026-06-20T10:00:00.000Z',
  },
  {
    id: 'p2',
    event_id: 'demo-event-1',
    user_id: null,
    name: '이준서',
    birth_date: '2011-07-22',
    gender: 'male',
    grade: '중2',
    phone: '010-2345-6789',
    parent_phone: '010-2222-3333',
    emergency_contact: '010-2222-3333',
    health_info: {},
    dietary_restrictions: null,
    transportation: 'bus',
    fee_paid: true,
    consent_personal_info: true,
    consent_sensitive_info: true,
    consent_photo_video: true,
    consent_overseas_transfer: false,
    consent_ip: null,
    created_at: '2026-06-20T10:05:00.000Z',
  },
  {
    id: 'p3',
    event_id: 'demo-event-1',
    user_id: null,
    name: '박하늘',
    birth_date: '2010-11-03',
    gender: 'female',
    grade: '중3',
    phone: '010-3456-7890',
    parent_phone: '010-3333-4444',
    emergency_contact: '010-3333-4444',
    health_info: { allergies: '견과류' },
    dietary_restrictions: '견과류 알레르기',
    transportation: 'self',
    fee_paid: false,
    consent_personal_info: true,
    consent_sensitive_info: true,
    consent_photo_video: true,
    consent_overseas_transfer: false,
    consent_ip: null,
    created_at: '2026-06-21T09:00:00.000Z',
  },
  {
    id: 'p4',
    event_id: 'demo-event-1',
    user_id: null,
    name: '최민준',
    birth_date: '2012-01-10',
    gender: 'male',
    grade: '중1',
    phone: '010-4567-8901',
    parent_phone: '010-4444-5555',
    emergency_contact: '010-4444-5555',
    health_info: {},
    dietary_restrictions: null,
    transportation: 'bus',
    fee_paid: true,
    consent_personal_info: true,
    consent_sensitive_info: true,
    consent_photo_video: true,
    consent_overseas_transfer: false,
    consent_ip: null,
    created_at: '2026-06-21T11:00:00.000Z',
  },
  {
    id: 'p5',
    event_id: 'demo-event-1',
    user_id: null,
    name: '정서연',
    birth_date: '2011-05-28',
    gender: 'female',
    grade: '중2',
    phone: '010-5678-9012',
    parent_phone: '010-5555-6666',
    emergency_contact: '010-5555-6666',
    health_info: {},
    dietary_restrictions: null,
    transportation: 'bus',
    fee_paid: true,
    consent_personal_info: true,
    consent_sensitive_info: true,
    consent_photo_video: false,
    consent_overseas_transfer: false,
    consent_ip: null,
    created_at: '2026-06-22T08:30:00.000Z',
  },
  {
    id: 'p6',
    event_id: 'demo-event-1',
    user_id: null,
    name: '강도현',
    birth_date: '2010-09-14',
    gender: 'male',
    grade: '중3',
    phone: '010-6789-0123',
    parent_phone: '010-6666-7777',
    emergency_contact: '010-6666-7777',
    health_info: {},
    dietary_restrictions: null,
    transportation: 'self',
    fee_paid: true,
    consent_personal_info: true,
    consent_sensitive_info: true,
    consent_photo_video: true,
    consent_overseas_transfer: false,
    consent_ip: null,
    created_at: '2026-06-22T09:00:00.000Z',
  },
  {
    id: 'p7',
    event_id: 'demo-event-1',
    user_id: null,
    name: '윤수빈',
    birth_date: '2012-06-01',
    gender: 'female',
    grade: '중1',
    phone: '010-7890-1234',
    parent_phone: '010-7777-8888',
    emergency_contact: '010-7777-8888',
    health_info: {},
    dietary_restrictions: null,
    transportation: 'bus',
    fee_paid: true,
    consent_personal_info: true,
    consent_sensitive_info: true,
    consent_photo_video: true,
    consent_overseas_transfer: false,
    consent_ip: null,
    created_at: '2026-06-23T10:00:00.000Z',
  },
  {
    id: 'p8',
    event_id: 'demo-event-1',
    user_id: null,
    name: '한지우',
    birth_date: '2011-12-25',
    gender: 'male',
    grade: '중2',
    phone: '010-8901-2345',
    parent_phone: '010-8888-9999',
    emergency_contact: '010-8888-9999',
    health_info: {},
    dietary_restrictions: '유제품 제한',
    transportation: 'bus',
    fee_paid: false,
    consent_personal_info: true,
    consent_sensitive_info: true,
    consent_photo_video: true,
    consent_overseas_transfer: false,
    consent_ip: null,
    created_at: '2026-06-23T14:00:00.000Z',
  },
  {
    id: 'p9',
    event_id: 'demo-event-1',
    user_id: null,
    name: '송예린',
    birth_date: '2010-04-18',
    gender: 'female',
    grade: '중3',
    phone: '010-9012-3456',
    parent_phone: '010-9999-0000',
    emergency_contact: '010-9999-0000',
    health_info: {},
    dietary_restrictions: null,
    transportation: 'self',
    fee_paid: true,
    consent_personal_info: true,
    consent_sensitive_info: true,
    consent_photo_video: true,
    consent_overseas_transfer: false,
    consent_ip: null,
    created_at: '2026-06-24T09:00:00.000Z',
  },
  {
    id: 'p10',
    event_id: 'demo-event-1',
    user_id: null,
    name: '임태현',
    birth_date: '2012-08-07',
    gender: 'male',
    grade: '중1',
    phone: '010-0123-4567',
    parent_phone: '010-1010-2020',
    emergency_contact: '010-1010-2020',
    health_info: {},
    dietary_restrictions: null,
    transportation: 'bus',
    fee_paid: true,
    consent_personal_info: true,
    consent_sensitive_info: true,
    consent_photo_video: true,
    consent_overseas_transfer: false,
    consent_ip: null,
    created_at: '2026-06-25T10:00:00.000Z',
  },
  {
    id: 'p11',
    event_id: 'demo-event-1',
    user_id: null,
    name: '오소희',
    birth_date: '2011-02-14',
    gender: 'female',
    grade: '중2',
    phone: '010-1122-3344',
    parent_phone: '010-3030-4040',
    emergency_contact: '010-3030-4040',
    health_info: {},
    dietary_restrictions: null,
    transportation: 'bus',
    fee_paid: true,
    consent_personal_info: true,
    consent_sensitive_info: true,
    consent_photo_video: true,
    consent_overseas_transfer: false,
    consent_ip: null,
    created_at: '2026-06-26T10:00:00.000Z',
  },
  {
    id: 'p12',
    event_id: 'demo-event-1',
    user_id: null,
    name: '배성민',
    birth_date: '2010-10-30',
    gender: 'male',
    grade: '중3',
    phone: '010-2233-4455',
    parent_phone: '010-5050-6060',
    emergency_contact: '010-5050-6060',
    health_info: {},
    dietary_restrictions: null,
    transportation: 'self',
    fee_paid: true,
    consent_personal_info: true,
    consent_sensitive_info: true,
    consent_photo_video: true,
    consent_overseas_transfer: false,
    consent_ip: null,
    created_at: '2026-06-27T10:00:00.000Z',
  },
  {
    id: 'p13',
    event_id: 'demo-event-1',
    user_id: null,
    name: '류지현',
    birth_date: '2012-04-22',
    gender: 'female',
    grade: '중1',
    phone: '010-3344-5566',
    parent_phone: '010-7070-8080',
    emergency_contact: '010-7070-8080',
    health_info: {},
    dietary_restrictions: null,
    transportation: 'bus',
    fee_paid: false,
    consent_personal_info: true,
    consent_sensitive_info: true,
    consent_photo_video: true,
    consent_overseas_transfer: false,
    consent_ip: null,
    created_at: '2026-06-28T10:00:00.000Z',
  },
  {
    id: 'p14',
    event_id: 'demo-event-1',
    user_id: null,
    name: '문현우',
    birth_date: '2011-09-05',
    gender: 'male',
    grade: '중2',
    phone: '010-4455-6677',
    parent_phone: '010-9090-1010',
    emergency_contact: '010-9090-1010',
    health_info: { asthma: true },
    dietary_restrictions: null,
    transportation: 'bus',
    fee_paid: true,
    consent_personal_info: true,
    consent_sensitive_info: true,
    consent_photo_video: true,
    consent_overseas_transfer: false,
    consent_ip: null,
    created_at: '2026-06-29T10:00:00.000Z',
  },
  {
    id: 'p15',
    event_id: 'demo-event-1',
    user_id: null,
    name: '신유진',
    birth_date: '2010-12-12',
    gender: 'female',
    grade: '중3',
    phone: '010-5566-7788',
    parent_phone: '010-1212-3434',
    emergency_contact: '010-1212-3434',
    health_info: {},
    dietary_restrictions: null,
    transportation: 'self',
    fee_paid: true,
    consent_personal_info: true,
    consent_sensitive_info: true,
    consent_photo_video: true,
    consent_overseas_transfer: false,
    consent_ip: null,
    created_at: '2026-06-30T10:00:00.000Z',
  },
]

// ============================================
// Demo Schedules (18 sessions across 4 days)
// ============================================

export const DEMO_SCHEDULES: Schedule[] = [
  // Day 1 (July 20)
  {
    id: 's1',
    event_id: 'demo-event-1',
    day_number: 1,
    date: '2026-07-20',
    title: '등록 및 입소',
    type: 'free',
    start_time: '14:00',
    end_time: '15:00',
    location: '본관 로비',
    speaker: null,
    description: '참가자 등록, 방 배정, 짐 정리',
    materials: null,
    order_index: 1,
    created_at: '2026-07-01T00:00:00.000Z',
  },
  {
    id: 's2',
    event_id: 'demo-event-1',
    day_number: 1,
    date: '2026-07-20',
    title: '오리엔테이션',
    type: 'special',
    start_time: '15:00',
    end_time: '16:00',
    location: '대예배실',
    speaker: null,
    description: '행사 안내, 조 편성, 일정 공유',
    materials: null,
    order_index: 2,
    created_at: '2026-07-01T00:00:00.000Z',
  },
  {
    id: 's3',
    event_id: 'demo-event-1',
    day_number: 1,
    date: '2026-07-20',
    title: '개회예배',
    type: 'worship',
    start_time: '16:00',
    end_time: '17:30',
    location: '대예배실',
    speaker: '김목사',
    description: '말씀: 요한복음 7:37-39 "생수의 강"',
    materials: null,
    order_index: 3,
    created_at: '2026-07-01T00:00:00.000Z',
  },
  {
    id: 's4',
    event_id: 'demo-event-1',
    day_number: 1,
    date: '2026-07-20',
    title: '저녁식사',
    type: 'meal',
    start_time: '18:00',
    end_time: '19:00',
    location: '식당',
    speaker: null,
    description: null,
    materials: null,
    order_index: 4,
    created_at: '2026-07-01T00:00:00.000Z',
  },
  {
    id: 's5',
    event_id: 'demo-event-1',
    day_number: 1,
    date: '2026-07-20',
    title: '레크리에이션',
    type: 'recreation',
    start_time: '19:30',
    end_time: '21:00',
    location: '운동장',
    speaker: null,
    description: '아이스브레이킹 + 조별 게임',
    materials: null,
    order_index: 5,
    created_at: '2026-07-01T00:00:00.000Z',
  },
  // Day 2 (July 21)
  {
    id: 's6',
    event_id: 'demo-event-1',
    day_number: 2,
    date: '2026-07-21',
    title: '아침 QT',
    type: 'study',
    start_time: '07:00',
    end_time: '07:30',
    location: '조별 장소',
    speaker: null,
    description: '개인 큐티 + 조별 나눔',
    materials: null,
    order_index: 1,
    created_at: '2026-07-01T00:00:00.000Z',
  },
  {
    id: 's7',
    event_id: 'demo-event-1',
    day_number: 2,
    date: '2026-07-21',
    title: '아침식사',
    type: 'meal',
    start_time: '07:30',
    end_time: '08:30',
    location: '식당',
    speaker: null,
    description: null,
    materials: null,
    order_index: 2,
    created_at: '2026-07-01T00:00:00.000Z',
  },
  {
    id: 's8',
    event_id: 'demo-event-1',
    day_number: 2,
    date: '2026-07-21',
    title: '오전예배',
    type: 'worship',
    start_time: '09:00',
    end_time: '10:30',
    location: '대예배실',
    speaker: '박전도사',
    description: '말씀: 시편 42편 "사슴이 시냇물을 찾기에"',
    materials: null,
    order_index: 3,
    created_at: '2026-07-01T00:00:00.000Z',
  },
  {
    id: 's9',
    event_id: 'demo-event-1',
    day_number: 2,
    date: '2026-07-21',
    title: '성경퀴즈',
    type: 'special',
    start_time: '11:00',
    end_time: '12:00',
    location: '대예배실',
    speaker: null,
    description: '조별 성경퀴즈 대회',
    materials: null,
    order_index: 4,
    created_at: '2026-07-01T00:00:00.000Z',
  },
  {
    id: 's10',
    event_id: 'demo-event-1',
    day_number: 2,
    date: '2026-07-21',
    title: '점심식사',
    type: 'meal',
    start_time: '12:00',
    end_time: '13:00',
    location: '식당',
    speaker: null,
    description: null,
    materials: null,
    order_index: 5,
    created_at: '2026-07-01T00:00:00.000Z',
  },
  {
    id: 's11',
    event_id: 'demo-event-1',
    day_number: 2,
    date: '2026-07-21',
    title: '수영 & 물놀이',
    type: 'recreation',
    start_time: '14:00',
    end_time: '16:00',
    location: '수영장',
    speaker: null,
    description: '자유 물놀이 시간 (안전요원 배치)',
    materials: null,
    order_index: 6,
    created_at: '2026-07-01T00:00:00.000Z',
  },
  {
    id: 's12',
    event_id: 'demo-event-1',
    day_number: 2,
    date: '2026-07-21',
    title: '찬양의 밤',
    type: 'worship',
    start_time: '19:00',
    end_time: '21:00',
    location: '대예배실',
    speaker: null,
    description: '찬양 콘서트 + 기도회',
    materials: null,
    order_index: 7,
    created_at: '2026-07-01T00:00:00.000Z',
  },
  // Day 3 (July 22)
  {
    id: 's13',
    event_id: 'demo-event-1',
    day_number: 3,
    date: '2026-07-22',
    title: '아침 QT',
    type: 'study',
    start_time: '07:00',
    end_time: '07:30',
    location: '조별 장소',
    speaker: null,
    description: '개인 큐티 + 조별 나눔',
    materials: null,
    order_index: 1,
    created_at: '2026-07-01T00:00:00.000Z',
  },
  {
    id: 's14',
    event_id: 'demo-event-1',
    day_number: 3,
    date: '2026-07-22',
    title: '오전예배',
    type: 'worship',
    start_time: '09:00',
    end_time: '10:30',
    location: '대예배실',
    speaker: '김목사',
    description: '말씀: 이사야 55:1 "목마른 자여"',
    materials: null,
    order_index: 2,
    created_at: '2026-07-01T00:00:00.000Z',
  },
  {
    id: 's15',
    event_id: 'demo-event-1',
    day_number: 3,
    date: '2026-07-22',
    title: '미션 활동',
    type: 'recreation',
    start_time: '11:00',
    end_time: '12:30',
    location: '수련원 전체',
    speaker: null,
    description: '조별 미션 수행 (보물찾기, 미션 클리어)',
    materials: null,
    order_index: 3,
    created_at: '2026-07-01T00:00:00.000Z',
  },
  {
    id: 's16',
    event_id: 'demo-event-1',
    day_number: 3,
    date: '2026-07-22',
    title: '바비큐 파티',
    type: 'meal',
    start_time: '17:00',
    end_time: '19:00',
    location: '야외 바비큐장',
    speaker: null,
    description: '야외 바비큐 + 조별 공연 준비',
    materials: null,
    order_index: 4,
    created_at: '2026-07-01T00:00:00.000Z',
  },
  {
    id: 's17',
    event_id: 'demo-event-1',
    day_number: 3,
    date: '2026-07-22',
    title: '장기자랑 & 시상',
    type: 'special',
    start_time: '19:30',
    end_time: '21:30',
    location: '대예배실',
    speaker: null,
    description: '조별 장기자랑 + 포인트 시상',
    materials: null,
    order_index: 5,
    created_at: '2026-07-01T00:00:00.000Z',
  },
  // Day 4 (July 23)
  {
    id: 's18',
    event_id: 'demo-event-1',
    day_number: 4,
    date: '2026-07-23',
    title: '폐회예배',
    type: 'worship',
    start_time: '09:00',
    end_time: '10:30',
    location: '대예배실',
    speaker: '김목사',
    description: '말씀: 요한복음 4:14 "영원히 목마르지 아니하리라"',
    materials: null,
    order_index: 1,
    created_at: '2026-07-01T00:00:00.000Z',
  },
  {
    id: 's19',
    event_id: 'demo-event-1',
    day_number: 4,
    date: '2026-07-23',
    title: '퇴소 및 정리',
    type: 'free',
    start_time: '11:00',
    end_time: '12:00',
    location: '본관 로비',
    speaker: null,
    description: '방 정리, 짐 수거, 퇴소',
    materials: null,
    order_index: 2,
    created_at: '2026-07-01T00:00:00.000Z',
  },
]

// ============================================
// Demo Groups (4 groups)
// ============================================

export const DEMO_GROUPS: Group[] = [
  {
    id: 'g1',
    event_id: 'demo-event-1',
    name: '1조 사랑',
    leader_id: null,
    color: '#38bdf8',
    total_points: 120,
    created_at: '2026-07-01T00:00:00.000Z',
  },
  {
    id: 'g2',
    event_id: 'demo-event-1',
    name: '2조 믿음',
    leader_id: null,
    color: '#22d3ee',
    total_points: 95,
    created_at: '2026-07-01T00:00:00.000Z',
  },
  {
    id: 'g3',
    event_id: 'demo-event-1',
    name: '3조 소망',
    leader_id: null,
    color: '#a78bfa',
    total_points: 110,
    created_at: '2026-07-01T00:00:00.000Z',
  },
  {
    id: 'g4',
    event_id: 'demo-event-1',
    name: '4조 기쁨',
    leader_id: null,
    color: '#34d399',
    total_points: 85,
    created_at: '2026-07-01T00:00:00.000Z',
  },
]

// ============================================
// Demo Group Members
// ============================================

export const DEMO_GROUP_MEMBERS: GroupMember[] = [
  // Group 1 (사랑): p1, p5, p9, p13
  { id: 'gm1', group_id: 'g1', participant_id: 'p1' },
  { id: 'gm2', group_id: 'g1', participant_id: 'p5' },
  { id: 'gm3', group_id: 'g1', participant_id: 'p9' },
  { id: 'gm4', group_id: 'g1', participant_id: 'p13' },
  // Group 2 (믿음): p2, p6, p10, p14
  { id: 'gm5', group_id: 'g2', participant_id: 'p2' },
  { id: 'gm6', group_id: 'g2', participant_id: 'p6' },
  { id: 'gm7', group_id: 'g2', participant_id: 'p10' },
  { id: 'gm8', group_id: 'g2', participant_id: 'p14' },
  // Group 3 (소망): p3, p7, p11, p15
  { id: 'gm9', group_id: 'g3', participant_id: 'p3' },
  { id: 'gm10', group_id: 'g3', participant_id: 'p7' },
  { id: 'gm11', group_id: 'g3', participant_id: 'p11' },
  { id: 'gm12', group_id: 'g3', participant_id: 'p15' },
  // Group 4 (기쁨): p4, p8, p12
  { id: 'gm13', group_id: 'g4', participant_id: 'p4' },
  { id: 'gm14', group_id: 'g4', participant_id: 'p8' },
  { id: 'gm15', group_id: 'g4', participant_id: 'p12' },
]

// ============================================
// Demo Attendance (Day 1 sessions only)
// ============================================

function generateAttendanceForSchedule(
  scheduleId: string,
  participantIds: string[],
  statuses: string[]
): AttendanceRecord[] {
  return participantIds.map((pid, i) => ({
    id: `att-${scheduleId}-${pid}`,
    schedule_id: scheduleId,
    participant_id: pid,
    status: statuses[i % statuses.length],
    checked_by: 'demo-user',
    checked_at: '2026-07-20T16:00:00.000Z',
  }))
}

const allParticipantIds = DEMO_PARTICIPANTS.map((p) => p.id)

export const DEMO_ATTENDANCE: AttendanceRecord[] = [
  // Day 1 - Opening worship (s3) - some late
  ...generateAttendanceForSchedule(
    's3',
    allParticipantIds,
    ['present', 'present', 'late', 'present', 'present', 'present', 'late', 'present', 'present', 'present', 'present', 'present', 'absent', 'present', 'present']
  ),
  // Day 1 - Recreation (s5)
  ...generateAttendanceForSchedule(
    's5',
    allParticipantIds,
    ['present', 'present', 'present', 'present', 'present', 'present', 'present', 'present', 'present', 'present', 'present', 'present', 'present', 'present', 'present']
  ),
  // Day 2 - Morning QT (s6) - some absent
  ...generateAttendanceForSchedule(
    's6',
    allParticipantIds,
    ['present', 'absent', 'present', 'late', 'present', 'present', 'absent', 'present', 'present', 'late', 'present', 'present', 'absent', 'present', 'present']
  ),
  // Day 2 - Morning worship (s8)
  ...generateAttendanceForSchedule(
    's8',
    allParticipantIds,
    ['present', 'present', 'present', 'present', 'present', 'present', 'present', 'present', 'present', 'present', 'present', 'present', 'late', 'present', 'present']
  ),
  // Day 2 - Quiz (s9)
  ...generateAttendanceForSchedule(
    's9',
    allParticipantIds,
    ['present', 'present', 'present', 'present', 'present', 'present', 'present', 'present', 'present', 'present', 'present', 'present', 'present', 'present', 'present']
  ),
]

// ============================================
// Demo Announcements
// ============================================

export const DEMO_ANNOUNCEMENTS: Announcement[] = [
  {
    id: 'a1',
    event_id: 'demo-event-1',
    title: '수련회 준비물 안내',
    content: '성경, 찬양집, 세면도구, 여벌 옷, 수건, 선크림을 준비해 주세요. 수영복도 꼭 챙겨오세요!',
    type: 'general',
    target_group_id: null,
    is_pinned: true,
    author_id: 'demo-user',
    created_at: '2026-07-18T09:00:00.000Z',
  },
  {
    id: 'a2',
    event_id: 'demo-event-1',
    title: '일정 변경 안내',
    content: '내일 오전 레크리에이션이 10시에서 10시 30분으로 변경되었어요. 참고해 주세요!',
    type: 'urgent',
    target_group_id: null,
    is_pinned: false,
    author_id: 'demo-user',
    created_at: '2026-07-20T20:00:00.000Z',
  },
  {
    id: 'a3',
    event_id: 'demo-event-1',
    title: '내일 물놀이 안내',
    content: '내일 오후 2시부터 수영장에서 물놀이가 있어요. 수영복과 수건을 꼭 준비해 주세요. 안전을 위해 버디 시스템을 운영해요.',
    type: 'general',
    target_group_id: null,
    is_pinned: false,
    author_id: 'demo-user',
    created_at: '2026-07-20T21:00:00.000Z',
  },
  {
    id: 'a4',
    event_id: 'demo-event-1',
    title: '1조 사랑 조별 모임',
    content: '내일 아침 QT 후 잠깐 조별 모임이 있어요. 조원 모두 참석해 주세요!',
    type: 'group',
    target_group_id: 'g1',
    is_pinned: false,
    author_id: 'demo-user',
    created_at: '2026-07-20T21:30:00.000Z',
  },
]

// ============================================
// Demo Quizzes
// ============================================

export const DEMO_QUIZZES: Quiz[] = [
  {
    id: 'q1',
    event_id: 'demo-event-1',
    title: '성경 퀴즈 1일차',
    description: '요한복음에서 출제되는 1일차 성경퀴즈예요',
    type: 'multiple_choice',
    is_active: true,
    time_limit: 30,
    points_per_question: 10,
    created_at: '2026-07-15T00:00:00.000Z',
  },
  {
    id: 'q2',
    event_id: 'demo-event-1',
    title: 'OX 퀴즈 2일차',
    description: '시편과 이사야에서 출제되는 OX 퀴즈예요',
    type: 'ox',
    is_active: false,
    time_limit: 15,
    points_per_question: 5,
    created_at: '2026-07-15T00:00:00.000Z',
  },
]

export const DEMO_QUIZ_QUESTIONS: QuizQuestion[] = [
  {
    id: 'qq1',
    quiz_id: 'q1',
    question: '"목마른 자는 내게로 와서 마시라"는 누가 한 말씀인가요?',
    type: 'multiple_choice',
    options: { A: '모세', B: '다윗', C: '예수님', D: '바울' },
    correct_answer: 'C',
    order_index: 1,
    points: 10,
  },
  {
    id: 'qq2',
    quiz_id: 'q1',
    question: '요한복음 7장에서 예수님이 말씀하신 "생수의 강"은 무엇을 의미하나요?',
    type: 'multiple_choice',
    options: { A: '요단강', B: '성령', C: '세례', D: '치유' },
    correct_answer: 'B',
    order_index: 2,
    points: 10,
  },
  {
    id: 'qq3',
    quiz_id: 'q1',
    question: '요한복음 4장에서 예수님이 우물가에서 만난 여인은 어디 사람인가요?',
    type: 'multiple_choice',
    options: { A: '유대', B: '갈릴리', C: '사마리아', D: '이두매' },
    correct_answer: 'C',
    order_index: 3,
    points: 10,
  },
  {
    id: 'qq4',
    quiz_id: 'q2',
    question: '"사슴이 시냇물을 찾기에"는 시편 42편의 내용이다.',
    type: 'ox',
    options: { O: '맞아요', X: '틀려요' },
    correct_answer: 'O',
    order_index: 1,
    points: 5,
  },
  {
    id: 'qq5',
    quiz_id: 'q2',
    question: '이사야 55장에서 "오라, 물을 구매하라"고 말한다.',
    type: 'ox',
    options: { O: '맞아요', X: '틀려요' },
    correct_answer: 'X',
    order_index: 2,
    points: 5,
  },
]

export const DEMO_QUIZ_RESPONSES: QuizResponse[] = [
  // Participant p1 answered quiz 1
  { id: 'qr1', question_id: 'qq1', participant_id: 'p1', answer: 'C', is_correct: true, time_taken: 8, points_earned: 10, created_at: '2026-07-21T11:10:00.000Z' },
  { id: 'qr2', question_id: 'qq2', participant_id: 'p1', answer: 'B', is_correct: true, time_taken: 12, points_earned: 10, created_at: '2026-07-21T11:11:00.000Z' },
  { id: 'qr3', question_id: 'qq3', participant_id: 'p1', answer: 'C', is_correct: true, time_taken: 5, points_earned: 10, created_at: '2026-07-21T11:12:00.000Z' },
  // Participant p2 answered quiz 1
  { id: 'qr4', question_id: 'qq1', participant_id: 'p2', answer: 'C', is_correct: true, time_taken: 15, points_earned: 10, created_at: '2026-07-21T11:10:00.000Z' },
  { id: 'qr5', question_id: 'qq2', participant_id: 'p2', answer: 'A', is_correct: false, time_taken: 20, points_earned: 0, created_at: '2026-07-21T11:11:00.000Z' },
  { id: 'qr6', question_id: 'qq3', participant_id: 'p2', answer: 'C', is_correct: true, time_taken: 10, points_earned: 10, created_at: '2026-07-21T11:12:00.000Z' },
  // Participant p3 answered quiz 1
  { id: 'qr7', question_id: 'qq1', participant_id: 'p3', answer: 'A', is_correct: false, time_taken: 25, points_earned: 0, created_at: '2026-07-21T11:10:00.000Z' },
  { id: 'qr8', question_id: 'qq2', participant_id: 'p3', answer: 'B', is_correct: true, time_taken: 18, points_earned: 10, created_at: '2026-07-21T11:11:00.000Z' },
  { id: 'qr9', question_id: 'qq3', participant_id: 'p3', answer: 'D', is_correct: false, time_taken: 22, points_earned: 0, created_at: '2026-07-21T11:12:00.000Z' },
]

// ============================================
// Demo Points
// ============================================

export const DEMO_POINTS: PointRecord[] = [
  // Group points
  { id: 'pt1', event_id: 'demo-event-1', participant_id: null, group_id: 'g1', category: 'activity', amount: 50, description: '레크리에이션 1등', created_at: '2026-07-20T21:00:00.000Z' },
  { id: 'pt2', event_id: 'demo-event-1', participant_id: null, group_id: 'g1', category: 'attendance', amount: 40, description: '출석 우수', created_at: '2026-07-21T07:30:00.000Z' },
  { id: 'pt3', event_id: 'demo-event-1', participant_id: null, group_id: 'g1', category: 'quiz', amount: 30, description: '성경퀴즈 우수', created_at: '2026-07-21T12:00:00.000Z' },
  { id: 'pt4', event_id: 'demo-event-1', participant_id: null, group_id: 'g2', category: 'activity', amount: 35, description: '레크리에이션 2등', created_at: '2026-07-20T21:00:00.000Z' },
  { id: 'pt5', event_id: 'demo-event-1', participant_id: null, group_id: 'g2', category: 'attendance', amount: 30, description: '출석 우수', created_at: '2026-07-21T07:30:00.000Z' },
  { id: 'pt6', event_id: 'demo-event-1', participant_id: null, group_id: 'g2', category: 'quiz', amount: 30, description: '성경퀴즈 우수', created_at: '2026-07-21T12:00:00.000Z' },
  { id: 'pt7', event_id: 'demo-event-1', participant_id: null, group_id: 'g3', category: 'activity', amount: 40, description: '레크리에이션 특별상', created_at: '2026-07-20T21:00:00.000Z' },
  { id: 'pt8', event_id: 'demo-event-1', participant_id: null, group_id: 'g3', category: 'attendance', amount: 35, description: '출석 우수', created_at: '2026-07-21T07:30:00.000Z' },
  { id: 'pt9', event_id: 'demo-event-1', participant_id: null, group_id: 'g3', category: 'quiz', amount: 35, description: '성경퀴즈 1등', created_at: '2026-07-21T12:00:00.000Z' },
  { id: 'pt10', event_id: 'demo-event-1', participant_id: null, group_id: 'g4', category: 'activity', amount: 30, description: '레크리에이션 참가상', created_at: '2026-07-20T21:00:00.000Z' },
  { id: 'pt11', event_id: 'demo-event-1', participant_id: null, group_id: 'g4', category: 'attendance', amount: 25, description: '출석', created_at: '2026-07-21T07:30:00.000Z' },
  { id: 'pt12', event_id: 'demo-event-1', participant_id: null, group_id: 'g4', category: 'quiz', amount: 30, description: '성경퀴즈 우수', created_at: '2026-07-21T12:00:00.000Z' },
  // Individual points
  { id: 'pt13', event_id: 'demo-event-1', participant_id: 'p1', group_id: 'g1', category: 'quiz', amount: 30, description: '성경퀴즈 만점', created_at: '2026-07-21T12:00:00.000Z' },
  { id: 'pt14', event_id: 'demo-event-1', participant_id: 'p2', group_id: 'g2', category: 'quiz', amount: 20, description: '성경퀴즈', created_at: '2026-07-21T12:00:00.000Z' },
  { id: 'pt15', event_id: 'demo-event-1', participant_id: 'p3', group_id: 'g3', category: 'quiz', amount: 10, description: '성경퀴즈', created_at: '2026-07-21T12:00:00.000Z' },
  { id: 'pt16', event_id: 'demo-event-1', participant_id: 'p6', group_id: 'g2', category: 'bonus', amount: 15, description: '봉사 활동', created_at: '2026-07-20T20:00:00.000Z' },
  { id: 'pt17', event_id: 'demo-event-1', participant_id: 'p9', group_id: 'g1', category: 'attendance', amount: 10, description: '개근상', created_at: '2026-07-21T18:00:00.000Z' },
]

// ============================================
// Demo Materials
// ============================================

export const DEMO_MATERIALS: Material[] = [
  {
    id: 'm1',
    event_id: 'demo-event-1',
    title: '찬양 악보집',
    category: 'hymn',
    file_url: '#',
    file_type: 'pdf',
    file_size: 2048000,
    day_number: null,
    uploaded_by: 'demo-user',
    created_at: '2026-07-15T10:00:00.000Z',
  },
  {
    id: 'm2',
    event_id: 'demo-event-1',
    title: '1일차 큐티 교재',
    category: 'textbook',
    file_url: '#',
    file_type: 'pdf',
    file_size: 1024000,
    day_number: 1,
    uploaded_by: 'demo-user',
    created_at: '2026-07-15T10:00:00.000Z',
  },
  {
    id: 'm3',
    event_id: 'demo-event-1',
    title: '2일차 큐티 교재',
    category: 'textbook',
    file_url: '#',
    file_type: 'pdf',
    file_size: 1124000,
    day_number: 2,
    uploaded_by: 'demo-user',
    created_at: '2026-07-15T10:00:00.000Z',
  },
  {
    id: 'm4',
    event_id: 'demo-event-1',
    title: '조별 활동 워크시트',
    category: 'worksheet',
    file_url: '#',
    file_type: 'pdf',
    file_size: 512000,
    day_number: 2,
    uploaded_by: 'demo-user',
    created_at: '2026-07-16T10:00:00.000Z',
  },
]

// ============================================
// Demo Gallery
// ============================================

export const DEMO_ALBUMS: GalleryAlbum[] = [
  {
    id: 'al1',
    event_id: 'demo-event-1',
    title: '1일차 - 입소 & 개회예배',
    day_number: 1,
    created_at: '2026-07-20T18:00:00.000Z',
  },
  {
    id: 'al2',
    event_id: 'demo-event-1',
    title: '2일차 - 물놀이 & 찬양의 밤',
    day_number: 2,
    created_at: '2026-07-21T20:00:00.000Z',
  },
]

export const DEMO_PHOTOS: GalleryPhoto[] = [
  {
    id: 'ph1',
    album_id: 'al1',
    file_url: '#',
    thumbnail_url: null,
    caption: '개회예배 찬양시간',
    uploaded_by: 'demo-user',
    created_at: '2026-07-20T17:00:00.000Z',
  },
  {
    id: 'ph2',
    album_id: 'al1',
    file_url: '#',
    thumbnail_url: null,
    caption: '입소 등록 현장',
    uploaded_by: 'demo-user',
    created_at: '2026-07-20T15:00:00.000Z',
  },
  {
    id: 'ph3',
    album_id: 'al1',
    file_url: '#',
    thumbnail_url: null,
    caption: '조별 사진',
    uploaded_by: 'demo-user',
    created_at: '2026-07-20T19:00:00.000Z',
  },
  {
    id: 'ph4',
    album_id: 'al2',
    file_url: '#',
    thumbnail_url: null,
    caption: '수영장 물놀이',
    uploaded_by: 'demo-user',
    created_at: '2026-07-21T15:00:00.000Z',
  },
  {
    id: 'ph5',
    album_id: 'al2',
    file_url: '#',
    thumbnail_url: null,
    caption: '찬양의 밤',
    uploaded_by: 'demo-user',
    created_at: '2026-07-21T20:00:00.000Z',
  },
]

// ============================================
// Demo User
// ============================================

export const DEMO_USER = {
  id: 'demo-user',
  name: '관리자 (데모)',
  role: 'admin' as const,
  phone: '010-0000-0000',
  avatarUrl: null,
  hasSeenOnboarding: true,
  created_at: new Date().toISOString(),
}
